### ISSUE TITLE
Can I use redis version 6?

### ISSUE THREAD

**Issue by Chohongjae** [supercharge/redis-github-action#2]
Hello I'm Cho
First of all, thanks to you, I am able to conduct a virtual test using redis.
Currently I am using redis version 6 in my server.
But your usage seems to only support versions 4 and 5, can I use 6?

Thanks.
Cho

**Comment by marcuspoehls** [comment]
@Chohongjae Hey Cho, thank you for reaching out!

Yep, you can use Redis 6.

Here’s how you can configure the GitHub Action to test your app against Redis 4, 5, and 6:

```yaml
name: Run tests

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [4, 5, 6]

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - name: Setup Node.js
      …

    - name: Run your tests
      …
```

You can also remove the Matrix items for Redis 4 and 5 and reduce it to `redis-version: [6]`

Does this work in your setup?
