### ISSUE TITLE
Support multiple flavor matrix?

### ISSUE THREAD

**Issue by mperham** [supercharge/redis-github-action#24]
I'd like to test my code against Dragonfly, Valkey and Redis. Is there a way to provide this type of matrix? I'd like to use something like:

```json
[
  ["valkey", "8"],
  ["dragonflydb", "1"],
  ["redis", "7"]
  ["redis", "6"]
]
```

but I'm unclear if this is possible to implement.

**Comment by marcuspoehls** [comment]
@mperham Hey Mike, this GitHub Action supports using a custom Redis Docker image. You might be able to use this Redis image in combination with your matrix.

Here’s my doodle on how I can imagine that a matrix with key-value pairs could work. I used  inspiration for key-value pairs in a GitHub Actions matrix from this thread: https://github.com/orgs/community/discussions/24981#discussioncomment-3246068

```yml
name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        database: [ 
          { image: "redis/redis-stack-server", version: "6" },
          { image: "redis/redis-stack-server", version: "7" },
          { image: "valkey/valkey", version: "8" },
          { image: "dragonflydb/dragonfly", version: "newest" }
        ]

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-image: ${{ matrix.database.image }}
        redis-version: ${{ matrix.database.version }}

    - name: …
```
